#!/usr/bin/env bash
#
# Build a static binary for the host OS/ARCH
#

set -eu -o pipefail

source /cross/.variables

echo "Building $TARGET"
go build -buildmode="${BUILDMODE}" -o "${TARGET}" -ldflags "${LDFLAGS}" "${SOURCE}"
